name: Using Poetry Publisher

on:
    workflow_dispatch:
        inputs:
            package_version:
                description: 'Version to publish'
                default: ''
                required: false
            poetry_version_bump:
                description: 'Options for poetry version command'
                default: 'patch'
                required: false
            python_version:
                description: 'Python version to use'
                default: '3.11'
                required: false
            poetry_build_options:
                description: 'Options for poetry build command'
                default: ''
                required: false
            run_pytest:
                description: 'Run tests with pytest'
                default: false
                type: boolean
            pytest_options:
                description: 'Options for pytest'
                default:
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Debug variables
              run: |
                  echo version = ${{ inputs.package_version }}
                  echo poetry_version_options = ${{ inputs.poetry_version_bump }}
                  echo python_version = ${{ inputs.python_version }}
                  echo poetry_build_options = ${{ inputs.poetry_build_options }}
                  echo run_pytest = ${{ inputs.run_pytest }}
                  echo pytest_options = ${{ inputs.pytest_options }}
                  echo PYPI_API_TOKEN = ${{ secrets.PYPI_API_TOKEN }}

            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ inputs.python_version }}
                  cache: 'pip'
                  check-latest: true

            - name: Poerty Publisher
              uses: ./actions/python-publisher
              with:
                package_version: ${{ inputs.package_version }}
                python-version: ${{ inputs.python-version }}
                poetry_version_bump: ${{ inputs.poetry_version_bump }}
                poetry_build_options: ${{ inputs.poetry_build_options }}
                run_pytest: ${{ inputs.run_pytest }}
                pytest_options: ${{ inputs.pytest_options }}
              env:
                PYPI_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}

