name: Pypy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Python version'
        required: true
        default: '3.11'
      []  
      pytest_run:
        description: 'Run tests'
        type: boolean
        required: true
        default: true  
jobs:
  build:
      uses: nookyo/workflow-hub/.github/workflows/python-build.yml@main
      with:
        python-version: ${{ inputs.version }}
        poetry_build_params: '--no-dev'
        pytest_run: ${{ inputs.run_tests }}
            