name: Pypy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Python version'
        required: true
        default: '3.11'
jobs:
  build:
      uses: nookyo/workflow-hub/.github/workflows/python-build.yml@main
      with:
        python-version: ${{ github.event.inputs.version }}
            